### 
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "mila", 
    "password": "mila",
    "name": "Wa Ode Kamila"
}

### 
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "idha", 
    "password": "idha"
}

### 
GET http://localhost:3000/api/users/current
Authorization: Unknown
