### 
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "mila", 
    "password": "mila",
    "name": "Wa Ode Kamila"
}

### 
POST https://my-portfolio-backend-express.vercel.app/api/users
Content-Type: application/json

{
    "username": "mila", 
    "password": "mila",
    "name": "Wa Ode Kamila"
}

### 
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "mila", 
    "password": "mila"
}

### 
GET http://localhost:3000/api/users/current
Authorization: 18c6c935-1eec-49d8-a42c-87ceda9251b2

### 
POST http://localhost:3000/api/myprojects
Authorization: 16380359-af50-42ab-9e2f-05bd234b483a
Content-Type: application/json

{
        "title": "test1",
        "tag": "reactNative,nodejs",
        "category": "mobile",
        "description": "test",
        "link_web": "test.web",
        "link_git": "test.git"
}

